### ISSUE TITLE
Previous Lab Requires Super

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/python-p3-super#1]
### Canvas Link

https://learning.flatironschool.com/courses/6049/pages/super?module_item_id=439036

### Concern

The second bullet point in the feedback for the lab immediately preceding this reading could have been addressed by using `super`, which students wouldn't have had knowledge of at that point. We could make connect these two things together - "remember in the previous lab when we had to redeclare the `__init__` function for our student since we wanted it to have another attribute? Look at how easy things become with `super`!" - or just modify it such that we only expect students to use `super` once they've been exposed to it.

**Comment by professor-ben** [comment]
I had big ideas for this one in the original iteration that don't seem to make much sense in context. I refactored this to use `super`, added information on `random`, and moved it to follow the `super` lesson and immediately precede python-p3-inheritance-lab-pt-2.

-Ben
