### ISSUE TITLE
General Writing Feedback 

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/python-p3-super#2]
### Canvas Link

https://learning.flatironschool.com/courses/6049/pages/super?module_item_id=439036

### Concern

**1.** In the 3rd paragraph of the **Calling `super` with Arguments** section, we have `... set it when an the class is instantiated.`. Should be `... set it when the class is instatiated.`

**Comment by professor-ben** [comment]
Fixed in July but the issue number got mixed up on GitHub and it stayed open all this time. Thanks for the report!

-Ben
